### ISSUE TITLE
swift?

### ISSUE THREAD

**Issue by josedom24** [iesgn/emergya#2]
¿Añadimos algo de swift?
Lo podemos meter en "Cinder y Swift", lo dejo indicado en http://iesgn.github.io/emergya/curso/u4/

Si se decide añadir, habría que hacer una documentación de swift en horizon.

**Comment by albertomolina** [comment]
En principio no. Además la instalación de OpenStack que se va a hacer para el curso no incluye Swift. 

Se podría poner al final en algún apartado del tipo "Otros temas" por si surge durante el curso, pero no vale la pena hacer la actualización poniendo Swift en Horizon, yo dejaría sólo CLI.
